In [1]:
import pandas as pd
import re

In [23]:
dados = pd.read_csv('house.csv')
dados

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63021,Thomastown,3/1 Travers St,3,u,NaN,PI,Barry,31/03/2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
63022,Williams Landing,1 Diadem Wy,4,h,NaN,SP,Aussie,31/03/2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

In [ ]:
filter1 = dados.loc[(dados['Rooms'] == 3) & (dados['Type'] == 'h') & (dados['Price'] <= 500000)] # where em aÃ§Ã£o
filter1

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
92,Broadmeadows,145 Graham St,3,h,457000.0,S,YPA,1/04/2017,3047,Northern Metropolitan,4294,14.0,Hume City Council
170,Craigieburn,7A Amstel St,3,h,356500.0,S,Jason,1/04/2017,3064,Northern Metropolitan,15510,20.6,Hume City Council
177,Cranbourne North,22 Horsfield St,3,h,475000.0,S,LJ,1/04/2017,3977,South-Eastern Metropolitan,6464,34.7,Casey City Council
183,Dallas,31 Phillip St,3,h,455500.0,S,Barry,1/04/2017,3047,Northern Metropolitan,2246,14.0,Hume City Council
192,Delahey,1/25 Yeats Dr,3,h,335000.0,S,Ray,1/04/2017,3037,Western Metropolitan,2898,18.0,Brimbank City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
62977,Werribee,4 Mekong Cl,3,h,420000.0,S,Barry,30/12/2017,3030,Western Metropolitan,16166,14.7,Wyndham City Council
62997,Wyndham Vale,5 Chatswood Pl,3,h,410000.0,S,hockingstuart,30/12/2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
62998,Wyndham Vale,21 Mermaid Cr,3,h,400000.0,SP,Barry,30/12/2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
63000,Wyndham Vale,8 Opala Ct,3,h,416000.0,S,Sweeney,30/12/2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council

In [21]:
filter2 = dados.loc[dados['Address'].str.contains('Turner St')] # o "in" padrÃ£o do python
filter2

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2859,Malvern East,24 Turner St,6,h,4700000.0,S,RT,3/03/2018,3145,Southern Metropolitan,8801,8.4,Stonnington City Council
4987,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
9647,Abbotsford,53 Turner St,2,h,NaN,S,Biggin,6/08/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
9648,Abbotsford,99 Turner St,2,h,NaN,S,Collins,6/08/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
14012,Berwick,4 Turner St,5,h,536000.0,S,O'Brien,8/04/2017,3806,Eastern Victoria,17093,35.2,Casey City Council
14745,Westmeadows,16 Turner St,3,h,NaN,SN,Stockdale,8/04/2017,3049,Northern Metropolitan,2474,16.5,Hume City Council
18960,Moonee Ponds,3/16 Turner St,2,u,550000.0,VB,Woodards,10/09/2016,3039,Western Metropolitan,6232,6.2,Moonee Valley City Council
19148,Abbotsford,106/119 Turner St,1,u,481000.0,SP,Purplebricks,10/12/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
20043,Westmeadows,14 Turner St,3,h,586000.0,S,Stockdale,10/12/2016,3049,Northern Metropolitan,2474,16.5,Hume City Council
25081,Moonee Ponds,15/3 Turner St,3,t,732000.0,S,Nelson,13/10/2018,3039,Western Metropolitan,6232,6.2,Moonee Valley City Council
26305,Abbotsford,2 Turner St,3,h,1620000.0,S,Biggin,14/07/2018,3067,Northern Metropolitan,4019,3.0,Yarra City Council
29650,Briar Hill,10 Turner St,2,h,812000.0,S,Darren,16/06/2018,3088,Eastern Metropolitan,1390,16.1,Banyule City Council
36217,Westmeadows,25 Turner St,4,h,685000.0,S,Jason,18/06/2016,3049,Northern Metropolitan,2474,16.5,Hume City Council
42537,Malvern East,16 Turner St,4,h,NaN,S,Marshall,22/05/2016,3145,Southern Metropolitan,8801,8.4,Stonnington City Council
47333,Malvern East,27 Turner St,2,h,1040000.0,S,Jellis,24/02/2018,3145,Southern Metropolitan,8801,8.4,Stonnington City Council
47843,Berwick,6 Turner St,4,h,1400000.0,VB,Peake,24/03/2018,3806,Eastern Victoria,17093,35.2,Casey City Council
49480,Abbotsford,31 Turner St,4,h,1542000.0,S,Collins,24/09/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
49890,Moonee Ponds,4/6 Turner St,2,u,600000.0,S,Woodards,24/09/2016,3039,Western Metropolitan,6232,6.2,Moonee Valley City Council
50254,Briar Hill,7 Turner St,4,h,1100000.0,S,Jellis,25/02/2017,3088,Eastern Metropolitan,1390,16.1,Banyule City Council
51364,Malvern East,29 Turner St,2,h,1010000.0,SP,Jellis,25/08/2018,3145,Southern Metropolitan,8801,8.4,Stonnington City Council
57940,Abbotsford,210/125 Turner St,2,u,760000.0,S,Nelson,28/07/2018,3067,Northern Metropolitan,4019,3.0,Yarra City Council
57978,Berwick,5 Turner St,4,h,940000.0,SP,Ray,28/07/2018,3806,Eastern Victoria,17093,35.2,Casey City Council

In [ ]:
filtro3 = dados.loc[dados['Address'].str.contains('turner st', flags=re.I)]
filtro3

Empty DataFrame
Columns: [Suburb, Address, Rooms, Type, Price, Method, SellerG, Date, Postcode, Regionname, Propertycount, Distance, CouncilArea]
Index: []

In [ ]:
filter4 = dados.loc[(dados['Address'].str.contains('^59', flags=re.I)) & (dados['Price'] < 500000)] # esse ^ garante que comeÃ§a com 59
filter4

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
2220,Wallan,59 William St,3,h,424000.0,S,Ruralco,2/06/2018,3756,Northern Victoria,3988,44.2,Mitchell Shire Council
9096,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,6/01/2018,3429,Western Metropolitan,14092,31.7,Hume City Council
13089,Sunshine West,59 Felstead Av,3,h,465000.0,S,Bells,7/11/2016,3020,Western Metropolitan,6763,10.5,Brimbank City Council
13840,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,8/01/2018,3429,Western Metropolitan,14092,31.7,Hume City Council
19616,Hoppers Crossing,59 Aitken Av,3,h,421600.0,SP,Barry,10/12/2016,3029,Western Metropolitan,13830,18.4,Wyndham City Council
19623,Hoppers Crossing,59 Mossfiel Dr,3,h,453000.0,S,Triwest,10/12/2016,3029,Western Metropolitan,13830,18.4,Wyndham City Council
30441,Thomastown,59 Darebin Dr,3,h,478500.0,S,hockingstuart,16/07/2016,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
31889,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,16/12/2017,3429,Western Metropolitan,14092,31.7,Hume City Council
46682,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,23/12/2017,3429,Western Metropolitan,14092,31.7,Hume City Council
62903,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,30/12/2017,3429,Western Metropolitan,14092,31.7,Hume City Council

In [ ]:
dados.loc[dados['SellerG'] == 'Nelson', 'SellerG'] = 'Ronaldo' # this method changes on this column for this value
dados

In [ ]:
dados.loc[dados['SellerG'] == 'Ronaldo', ['Method', 'Regionname']] = 'Teste' # onde o seller for ronaldo, na coluna "method" troque para P, n Ã© mto intuitivo
dados

In [38]:
apresentar = dados.groupby(['SellerG']).sum(['Price'])
apresentar.sort_values(['Price'], ascending=False).head(10) # isso aq ve o top 10 vendedores baseado no PREÃ‡O

               Rooms         Price  Postcode  Propertycount  Distance
SellerG
Jellis         16948  5.301902e+09  17116422       42958979   47831.6
Nelson         13808  4.089097e+09  14489179       35455466   34410.5
Barry          22919  4.022899e+09  21405391       54662639  108662.2
Marshall        9437  3.337732e+09   8949613       22270034   20141.4
hockingstuart  12635  3.174822e+09  13571171       36291698   53918.3
Buxton         10707  3.103258e+09  10669223       21365913   48190.6
Ray            14961  2.953669e+09  14329293       41191735   76239.1
Fletchers       5402  1.384292e+09   5039345       10521475   21963.2
Biggin          4203  1.002292e+09   4783284       12904764   12250.2
Noel            3447  9.618405e+08   3328766        6571572   14386.3

In [43]:
aprsentar = dados.groupby(['SellerG']).sum(['Rooms']) # note que sum Ã© um mÃ©todo do group by, entÃ£o precisa ficar groupby().sum(), sacou?
apresentar.sort_values(['Rooms'], ascending=False).head(10)

               Rooms         Price  Postcode  Propertycount  Distance
SellerG
Barry          22919  4.022899e+09  21405391       54662639  108662.2
Jellis         16948  5.301902e+09  17116422       42958979   47831.6
Ray            14961  2.953669e+09  14329293       41191735   76239.1
Nelson         13808  4.089097e+09  14489179       35455466   34410.5
hockingstuart  12635  3.174822e+09  13571171       36291698   53918.3
Buxton         10707  3.103258e+09  10669223       21365913   48190.6
Marshall        9437  3.337732e+09   8949613       22270034   20141.4
Fletchers       5402  1.384292e+09   5039345       10521475   21963.2
Biggin          4203  1.002292e+09   4783284       12904764   12250.2
Harcourts       4086  7.851802e+08   3877544       11905589   21653.0

In [47]:
aprsentar = dados.groupby(['SellerG'])['Rooms'].count()
apresentar.sort_values(['Rooms'], ascending=False).head(10)

               Rooms         Price  Postcode  Propertycount  Distance
SellerG
Barry          22919  4.022899e+09  21405391       54662639  108662.2
Jellis         16948  5.301902e+09  17116422       42958979   47831.6
Ray            14961  2.953669e+09  14329293       41191735   76239.1
Nelson         13808  4.089097e+09  14489179       35455466   34410.5
hockingstuart  12635  3.174822e+09  13571171       36291698   53918.3
Buxton         10707  3.103258e+09  10669223       21365913   48190.6
Marshall        9437  3.337732e+09   8949613       22270034   20141.4
Fletchers       5402  1.384292e+09   5039345       10521475   21963.2
Biggin          4203  1.002292e+09   4783284       12904764   12250.2
Harcourts       4086  7.851802e+08   3877544       11905589   21653.0